services:
  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: restaurant_django
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
  database:
    image: postgres:15
    container_name: restaurant_database
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  postgres_data:
