services:
  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: restaurant_django
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
