# Generated by Django 5.1.7 on 2025-03-15 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.PositiveSmallIntegerField(choices=[(0, 'DELIVERY'), (1, 'PICKUP')])),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до замовлення')),
                ('is_quickly', models.BooleanField(blank=True, default=False, null=True, verbose_name='Якнайшвидше?')),
                ('tableware_amount', models.PositiveSmallIntegerField(verbose_name='Кількість приладів')),
                ('has_specific_time', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доставка на конкретний час?')),
                ('desired_time', models.TimeField(blank=True, default=None, null=True, verbose_name='Час отримання замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('products', models.ManyToManyField(related_name='order_products', to='menu.provision', verbose_name='Продукти')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час платежу')),
                ('cash_given', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Купюра')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payment', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Оплата готівкою',
                'verbose_name_plural': 'Оплати готівкою',
            },
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час платежу')),
                ('card_last_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='Останні 4 цифри картки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payment', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Оплата карткою',
                'verbose_name_plural': 'Оплати картками',
            },
        ),
        migrations.CreateModel(
            name='TerminalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час платежу')),
                ('terminal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID терміналу')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payment', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Оплата через термінал',
                'verbose_name_plural': 'Оплати через термінали',
            },
        ),
    ]
