# Generated by Django 5.1.7 on 2025-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "card_last_digits",
                    models.CharField(max_length=4, verbose_name="Card last 4 numbers"),
                ),
            ],
            options={
                "verbose_name": "Card payment",
                "verbose_name_plural": "Card payments",
            },
        ),
        migrations.CreateModel(
            name="CashPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "cash_given",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Купюра"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash payment",
                "verbose_name_plural": "Cash payments",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "delivery_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "DELIVERY"), (1, "PICKUP")],
                        verbose_name="Delivery type",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Delivery address",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comment to order"
                    ),
                ),
                (
                    "is_quickly",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="As soon as possible?",
                    ),
                ),
                (
                    "tableware_amount",
                    models.PositiveSmallIntegerField(verbose_name="Tableware amount"),
                ),
                (
                    "desired_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Час отримання замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="TerminalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(max_length=50, verbose_name="Terminal ID"),
                ),
            ],
            options={
                "verbose_name": "Terminal payment",
                "verbose_name_plural": "Terminal payments",
            },
        ),
    ]
