# Generated by Django 5.1.7 on 2025-05-31 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="order_products",
                to="menu.provision",
                verbose_name="Products",
            ),
        ),
        migrations.AddField(
            model_name="cashpayment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_payment",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="cardpayment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_payment",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="terminalpayment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_payment",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
    ]
