# Generated by Django 5.1.7 on 2025-04-21 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now=True, verbose_name='Час на коли зарезервовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Час останнього оновлення')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хто зробив бронь')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='Бронь столика')),
            ],
        ),
    ]
