# Generated by Django 5.1.7 on 2025-05-31 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Who created reservation",
            ),
        ),
        migrations.AddField(
            model_name="reserve",
            name="table",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.table",
                verbose_name="Бронь столика",
            ),
        ),
    ]
