# Generated by Django 5.1.7 on 2025-05-31 08:06

import menu.utils.provision
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProvisionMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Menu")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Provision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Provision name"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=menu.utils.provision.provision_image_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("calories", models.PositiveSmallIntegerField(verbose_name="Calories")),
                ("grams", models.PositiveSmallIntegerField(verbose_name="Weight")),
                (
                    "menus",
                    models.ManyToManyField(
                        related_name="dishes",
                        to="menu.provisionmenu",
                        verbose_name="Dishes menu's",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
