# Generated by Django 5.1.7 on 2025-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("text", models.TextField(max_length=500, verbose_name="Comment text")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Is comment approved?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
